// ─── 20 СТРАН ─────────────────────────────────────────────────────
export const COUNTRIES = [
  {
    slug: 'thailand',
    name: 'Таиланд',
    flag: '🇹🇭',
    region: 'ЮВА',
    priority: ['real-estate', 'visa', 'business'],
    chi: {
      signal: 'yellow',
      index: 56,
      longTerm: 63,
      midTerm: 52,
      shortTerm: 48,
      agentNote: 'Таиланд в начале делевериджа. Ставка BOT на историческом минимуме 1%, но долг домохозяйств 88% ВВП и слабый ВВП 1.6% ограничивают рост. Краткосрочная линия падает быстрее среднесрочной — тренд нисходящий.',
      history: [
        { date: '2020-Q1', longTerm: 68, midTerm: 45, shortTerm: 28 },
        { date: '2020-Q3', longTerm: 67, midTerm: 35, shortTerm: 22 },
        { date: '2021-Q1', longTerm: 67, midTerm: 30, shortTerm: 20 },
        { date: '2021-Q3', longTerm: 66, midTerm: 32, shortTerm: 25 },
        { date: '2022-Q1', longTerm: 66, midTerm: 40, shortTerm: 35 },
        { date: '2022-Q3', longTerm: 65, midTerm: 44, shortTerm: 38 },
        { date: '2023-Q1', longTerm: 65, midTerm: 48, shortTerm: 40 },
        { date: '2023-Q3', longTerm: 65, midTerm: 47, shortTerm: 36 },
        { date: '2024-Q1', longTerm: 64, midTerm: 46, shortTerm: 34 },
        { date: '2024-Q3', longTerm: 64, midTerm: 44, shortTerm: 35 },
        { date: '2025-Q1', longTerm: 63, midTerm: 43, shortTerm: 36 },
        { date: '2025-Q3', longTerm: 63, midTerm: 42, shortTerm: 38 },
        { date: '2026-Q1', longTerm: 62, midTerm: 52, shortTerm: 48 },
      ],
      forecast: {
        base:     { label: 'Базовый',    probability: 60, chiIn5y: 55, chiIn10y: 62, description: 'Медленное восстановление. Долг домохозяйств снижается к 80%, туризм стабилен.' },
        positive: { label: 'Позитивный', probability: 25, chiIn5y: 68, chiIn10y: 74, description: 'Реформы привлекают FDI. Новые права собственности для иностранцев. ВВП ускоряется.' },
        negative: { label: 'Негативный', probability: 15, chiIn5y: 40, chiIn10y: 45, description: 'Политическая нестабильность усиливается. Туризм не восстанавливается. Долговой кризис.' },
      },
      factors: [
        { title: 'BOT снизил ставку до 1.0%', impact: 'positive', date: 'Февраль 2026' },
        { title: 'WB снизил прогноз ВВП до 1.6%', impact: 'negative', date: 'Январь 2026' },
        { title: 'Циклон Senyar — ущерб $2.1 млрд', impact: 'negative', date: 'Октябрь 2025' },
        { title: 'Туристы: 36 млн за 2025 год', impact: 'positive', date: 'Январь 2026' },
      ],
    },
    capitalFlow: {
      score: 48,
      signal: 'yellow',
      fdi: { value: 8.2, yoy: -12, trend: 'down', history: [{ year: 2021, value: 11.2 }, { year: 2022, value: 10.1 }, { year: 2023, value: 9.4 }, { year: 2024, value: 8.8 }, { year: 2025, value: 8.2 }] },
      portfolio: { value: -1.4, yoy: -40, trend: 'down', history: [{ year: 2021, value: 2.1 }, { year: 2022, value: 0.8 }, { year: 2023, value: -0.5 }, { year: 2024, value: -1.0 }, { year: 2025, value: -1.4 }] },
      remittances: { value: 7.8, yoy: 4, trend: 'up', history: [{ year: 2021, value: 6.2 }, { year: 2022, value: 6.8 }, { year: 2023, value: 7.1 }, { year: 2024, value: 7.5 }, { year: 2025, value: 7.8 }] },
      reForeign: { value: 2.1, yoy: 8, trend: 'up', history: [{ year: 2021, value: 0.8 }, { year: 2022, value: 1.2 }, { year: 2023, value: 1.7 }, { year: 2024, value: 1.9 }, { year: 2025, value: 2.1 }] },
      geoStructure: [
        { country: 'Китай', share: 28, flag: '🇨🇳' },
        { country: 'Япония', share: 18, flag: '🇯🇵' },
        { country: 'США', share: 12, flag: '🇺🇸' },
        { country: 'Европа', share: 22, flag: '🇪🇺' },
        { country: 'Другие', share: 20, flag: '🌍' },
      ],
    },
    macro: {
      gdpGrowth: 1.6, inflation: -0.2, cbRate: 1.0, unemployment: 1.1,
      householdDebt: 88, govDebt: 65, tradeBalance: 1.8,
      gdpPerCapita: 7300, population: 71.8, currency: 'THB', updatedAt: 'Март 2026',
    },
    society: { happinessRank: 54, happinessScore: 5.9, hdi: 0.800, gini: 43.3, democracyIndex: 4.6, medianAge: 42.5, populationGrowth: 0.1, militarySafety: 62 },
  },
  {
    slug: 'uae',
    name: 'ОАЭ',
    flag: '🇦🇪',
    region: 'Ближний Восток',
    priority: ['real-estate', 'business', 'visa'],
    chi: {
      signal: 'green',
      index: 74,
      longTerm: 78,
      midTerm: 74,
      shortTerm: 71,
      agentNote: 'ОАЭ — один из самых сильных рынков в мире прямо сейчас. FDI растёт, туристы бьют рекорды, новые визовые программы привлекают таланты. Все три линии на высоком уровне и синхронны.',
      history: [
        { date: '2021-Q1', longTerm: 72, midTerm: 62, shortTerm: 58 },
        { date: '2022-Q1', longTerm: 74, midTerm: 68, shortTerm: 65 },
        { date: '2023-Q1', longTerm: 76, midTerm: 72, shortTerm: 70 },
        { date: '2024-Q1', longTerm: 77, midTerm: 73, shortTerm: 72 },
        { date: '2025-Q1', longTerm: 78, midTerm: 74, shortTerm: 71 },
        { date: '2026-Q1', longTerm: 78, midTerm: 74, shortTerm: 71 },
      ],
      forecast: {
        base:     { label: 'Базовый',    probability: 55, chiIn5y: 76, chiIn10y: 74, description: 'Стабильный рост. Диверсификация экономики продолжается.' },
        positive: { label: 'Позитивный', probability: 30, chiIn5y: 82, chiIn10y: 84, description: 'ОАЭ становится глобальным хабом. Финтех и ИИ привлекают новые компании.' },
        negative: { label: 'Негативный', probability: 15, chiIn5y: 65, chiIn10y: 62, description: 'Геополитическая эскалация в регионе. Нефть ниже $50. Отток капитала.' },
      },
      factors: [
        { title: 'FDI вырос на 34% — рекорд', impact: 'positive', date: 'Январь 2026' },
        { title: 'Golden Visa расширена', impact: 'positive', date: 'Декабрь 2025' },
        { title: 'Туристов 22.6 млн в 2025', impact: 'positive', date: 'Январь 2026' },
      ],
    },
    capitalFlow: {
      score: 82, signal: 'green',
      fdi: { value: 30.4, yoy: 34, trend: 'up', history: [{ year: 2021, value: 20.7 }, { year: 2022, value: 22.7 }, { year: 2023, value: 25.1 }, { year: 2024, value: 27.8 }, { year: 2025, value: 30.4 }] },
      portfolio: { value: 8.2, yoy: 15, trend: 'up', history: [{ year: 2021, value: 5.1 }, { year: 2022, value: 6.2 }, { year: 2023, value: 6.8 }, { year: 2024, value: 7.1 }, { year: 2025, value: 8.2 }] },
      remittances: { value: -42.1, yoy: 3, trend: 'flat', history: [] },
      reForeign: { value: 18.5, yoy: 22, trend: 'up', history: [{ year: 2021, value: 8.2 }, { year: 2022, value: 11.4 }, { year: 2023, value: 14.2 }, { year: 2024, value: 15.8 }, { year: 2025, value: 18.5 }] },
      geoStructure: [{ country: 'Индия', share: 22, flag: '🇮🇳' }, { country: 'Китай', share: 18, flag: '🇨🇳' }, { country: 'Европа', share: 25, flag: '🇪🇺' }, { country: 'США', share: 15, flag: '🇺🇸' }, { country: 'Другие', share: 20, flag: '🌍' }],
    },
    macro: { gdpGrowth: 4.2, inflation: 2.3, cbRate: 5.15, unemployment: 2.7, householdDebt: 55, govDebt: 30, tradeBalance: 8.4, gdpPerCapita: 49000, population: 10.0, currency: 'AED', updatedAt: 'Март 2026' },
    society: { happinessRank: 22, happinessScore: 6.7, hdi: 0.911, gini: 32.5, democracyIndex: 2.8, medianAge: 34.1, populationGrowth: 1.5, militarySafety: 58 },
  },
  {
    slug: 'georgia',
    name: 'Грузия',
    flag: '🇬🇪',
    region: 'СНГ',
    priority: ['real-estate', 'business', 'visa'],
    chi: {
      signal: 'green', index: 68, longTerm: 65, midTerm: 68, shortTerm: 72,
      agentNote: 'Грузия — лучшее соотношение риск/возможности в регионе. Низкие налоги, простое открытие бизнеса, растущий туризм. Краткосрочная линия выше среднесрочной — тренд восходящий.',
      history: [
        { date: '2021-Q1', longTerm: 58, midTerm: 55, shortTerm: 52 },
        { date: '2022-Q1', longTerm: 60, midTerm: 62, shortTerm: 68 },
        { date: '2023-Q1', longTerm: 62, midTerm: 65, shortTerm: 70 },
        { date: '2024-Q1', longTerm: 63, midTerm: 66, shortTerm: 70 },
        { date: '2025-Q1', longTerm: 64, midTerm: 67, shortTerm: 71 },
        { date: '2026-Q1', longTerm: 65, midTerm: 68, shortTerm: 72 },
      ],
      forecast: {
        base:     { label: 'Базовый',    probability: 55, chiIn5y: 70, chiIn10y: 68, description: 'Устойчивый рост. Туризм и IT-сектор остаются драйверами.' },
        positive: { label: 'Позитивный', probability: 30, chiIn5y: 76, chiIn10y: 78, description: 'Евроинтеграция ускоряется. Прямые инвестиции из ЕС растут.' },
        negative: { label: 'Негативный', probability: 15, chiIn5y: 55, chiIn10y: 50, description: 'Геополитическое давление. Политическая нестабильность усиливается.' },
      },
      factors: [
        { title: 'ВВП рост 8.2% в 2025', impact: 'positive', date: 'Январь 2026' },
        { title: 'Туристов 7.1 млн — рекорд', impact: 'positive', date: 'Январь 2026' },
        { title: 'Политические протесты в Тбилиси', impact: 'negative', date: 'Ноябрь 2025' },
      ],
    },
    capitalFlow: {
      score: 71, signal: 'green',
      fdi: { value: 2.1, yoy: 18, trend: 'up', history: [{ year: 2021, value: 1.1 }, { year: 2022, value: 1.4 }, { year: 2023, value: 1.6 }, { year: 2024, value: 1.8 }, { year: 2025, value: 2.1 }] },
      portfolio: { value: 0.4, yoy: 12, trend: 'up', history: [] },
      remittances: { value: 3.8, yoy: 8, trend: 'up', history: [] },
      reForeign: { value: 1.2, yoy: 25, trend: 'up', history: [] },
      geoStructure: [{ country: 'Россия/СНГ', share: 35, flag: '🇷🇺' }, { country: 'Европа', share: 28, flag: '🇪🇺' }, { country: 'США', share: 15, flag: '🇺🇸' }, { country: 'Израиль', share: 10, flag: '🇮🇱' }, { country: 'Другие', share: 12, flag: '🌍' }],
    },
    macro: { gdpGrowth: 8.2, inflation: 3.1, cbRate: 8.25, unemployment: 15.6, householdDebt: 42, govDebt: 40, tradeBalance: -8.2, gdpPerCapita: 7100, population: 3.7, currency: 'GEL', updatedAt: 'Март 2026' },
    society: { happinessRank: 68, happinessScore: 5.5, hdi: 0.802, gini: 36.4, democracyIndex: 5.3, medianAge: 38.6, populationGrowth: -0.2, militarySafety: 52 },
  },

  // ─── Остальные 17 стран ─────────────────────────────────────────
  ...([
    { slug: 'turkey',      name: 'Турция',            flag: '🇹🇷', region: 'Ближний Восток',   priority: ['real-estate', 'visa'],             signal: 'yellow', index: 44, lt: 48, mt: 44, st: 40, gdp: 2.8,  infl: 65.2, rate: 45.0,  pop: 85.3,  note: 'Высокая инфляция остаётся главным риском. Недвижимость интересна для входа но требует хеджирования валютного риска.' },
    { slug: 'indonesia',   name: 'Индонезия',         flag: '🇮🇩', region: 'ЮВА',              priority: ['real-estate', 'visa'],             signal: 'green',  index: 65, lt: 64, mt: 65, st: 67, gdp: 5.1,  infl: 2.8,  rate: 5.75,  pop: 277.5, note: 'Одна из самых быстрорастущих экономик ЮВА. Бали остаётся топовым направлением для недвижимости.' },
    { slug: 'cyprus',      name: 'Кипр',              flag: '🇨🇾', region: 'Европа',            priority: ['visa', 'business'],               signal: 'green',  index: 70, lt: 72, mt: 70, st: 68, gdp: 3.2,  infl: 2.1,  rate: 4.25,  pop: 1.2,   note: 'Европейская юрисдикция с благоприятным налоговым режимом. Идеально для бизнеса и ВНЖ.' },
    { slug: 'portugal',    name: 'Португалия',        flag: '🇵🇹', region: 'Европа',            priority: ['visa', 'real-estate'],            signal: 'yellow', index: 62, lt: 65, mt: 62, st: 58, gdp: 2.1,  infl: 2.4,  rate: 4.25,  pop: 10.3,  note: 'Golden Visa изменена но страна остаётся привлекательной для ВНЖ и переезда.' },
    { slug: 'serbia',      name: 'Сербия',            flag: '🇷🇸', region: 'Европа',            priority: ['real-estate', 'business', 'visa'], signal: 'green',  index: 66, lt: 63, mt: 66, st: 70, gdp: 4.1,  infl: 4.8,  rate: 5.5,   pop: 6.8,   note: 'Растущий рынок недвижимости с низким порогом входа. Белград — новый хаб для IT и бизнеса.' },
    { slug: 'kazakhstan',  name: 'Казахстан',         flag: '🇰🇿', region: 'СНГ',               priority: ['business', 'visa'],               signal: 'yellow', index: 55, lt: 58, mt: 55, st: 52, gdp: 3.8,  infl: 8.4,  rate: 14.25, pop: 19.6,  note: 'Алматы активно развивается. Хорошая база для бизнеса в СНГ но высокая зависимость от нефти.' },
    { slug: 'vietnam',     name: 'Вьетнам',           flag: '🇻🇳', region: 'ЮВА',              priority: ['real-estate', 'business'],         signal: 'green',  index: 67, lt: 65, mt: 67, st: 70, gdp: 6.8,  infl: 3.2,  rate: 4.5,   pop: 98.2,  note: 'Один из самых динамичных рынков ЮВА. Ограничения для иностранцев в недвижимости смягчаются.' },
    { slug: 'malaysia',    name: 'Малайзия',          flag: '🇲🇾', region: 'ЮВА',              priority: ['real-estate', 'visa'],            signal: 'green',  index: 66, lt: 67, mt: 66, st: 64, gdp: 4.4,  infl: 2.0,  rate: 3.0,   pop: 33.6,  note: 'Стабильная экономика, программа MM2H привлекает иностранцев. Рынок недвижимости восстанавливается.' },
    { slug: 'spain',       name: 'Испания',           flag: '🇪🇸', region: 'Европа',            priority: ['real-estate', 'visa'],            signal: 'yellow', index: 60, lt: 63, mt: 60, st: 56, gdp: 2.5,  infl: 2.8,  rate: 4.25,  pop: 47.8,  note: 'Золотая виза отменена но рынок недвижимости остаётся сильным особенно на побережье.' },
    { slug: 'uzbekistan',  name: 'Узбекистан',        flag: '🇺🇿', region: 'СНГ',               priority: ['business', 'real-estate'],        signal: 'yellow', index: 52, lt: 50, mt: 52, st: 55, gdp: 6.2,  infl: 10.1, rate: 13.0,  pop: 36.5,  note: 'Быстро реформирующаяся экономика. Ташкент привлекает инвесторов но риски всё ещё высоки.' },
    { slug: 'israel',      name: 'Израиль',           flag: '🇮🇱', region: 'Ближний Восток',   priority: ['business', 'stock-market'],       signal: 'yellow', index: 54, lt: 62, mt: 54, st: 46, gdp: 1.8,  infl: 3.4,  rate: 4.5,   pop: 9.8,   note: 'Высокий потенциал тех-сектора но геополитические риски давят на краткосрочный сигнал.' },
    { slug: 'india',       name: 'Индия',             flag: '🇮🇳', region: 'Азия',              priority: ['stock-market', 'business'],       signal: 'green',  index: 71, lt: 72, mt: 71, st: 70, gdp: 7.0,  infl: 4.8,  rate: 6.5,   pop: 1441,  note: 'Крупнейший рынок будущего. Фондовый рынок показывает устойчивый рост уже несколько лет.' },
    { slug: 'germany',     name: 'Германия',          flag: '🇩🇪', region: 'Европа',            priority: ['stock-market', 'business'],       signal: 'yellow', index: 57, lt: 68, mt: 57, st: 48, gdp: 0.2,  infl: 2.3,  rate: 4.25,  pop: 84.1,  note: 'Структурные проблемы в промышленности. Долгосрочно сильная страна но среднесрочно слабая.' },
    { slug: 'uk',          name: 'Британия',          flag: '🇬🇧', region: 'Европа',            priority: ['stock-market', 'real-estate'],    signal: 'yellow', index: 60, lt: 65, mt: 60, st: 58, gdp: 1.1,  infl: 2.8,  rate: 4.5,   pop: 68.4,  note: 'Пост-Brexit адаптация завершается. Лондонский рынок недвижимости стабилизировался.' },
    { slug: 'china',       name: 'Китай',             flag: '🇨🇳', region: 'Азия',              priority: ['stock-market'],                  signal: 'yellow', index: 55, lt: 65, mt: 55, st: 48, gdp: 4.6,  infl: 0.1,  rate: 3.1,   pop: 1408,  note: 'Дефляционные риски и кризис недвижимости. Долгосрочный потенциал сохраняется.' },
    { slug: 'usa',         name: 'США',               flag: '🇺🇸', region: 'Северная Америка', priority: ['stock-market'],                  signal: 'green',  index: 72, lt: 74, mt: 72, st: 71, gdp: 2.8,  infl: 2.4,  rate: 4.25,  pop: 335,   note: 'Фондовый рынок на рекордных уровнях. ФРС завершает цикл снижения ставок.' },
    { slug: 'russia',      name: 'Россия',            flag: '🇷🇺', region: 'СНГ',               priority: [],                                signal: 'red',    index: 28, lt: 32, mt: 28, st: 24, gdp: -1.2, infl: 9.4,  rate: 21.0,  pop: 144,   note: 'Санкционное давление и военный конфликт создают системные риски. Только аналитический контекст.' },
  ]).map(c => ({
    slug: c.slug,
    name: c.name,
    flag: c.flag,
    region: c.region,
    priority: [...c.priority],
    chi: {
      signal: c.signal,
      index: c.index,
      longTerm: c.lt,
      midTerm: c.mt,
      shortTerm: c.st,
      agentNote: c.note,
      history: [
        { date: '2022-Q1', longTerm: c.lt - 4, midTerm: c.mt - 6, shortTerm: c.st - 8 },
        { date: '2023-Q1', longTerm: c.lt - 2, midTerm: c.mt - 3, shortTerm: c.st - 4 },
        { date: '2024-Q1', longTerm: c.lt - 1, midTerm: c.mt - 1, shortTerm: c.st - 2 },
        { date: '2025-Q1', longTerm: c.lt,     midTerm: c.mt - 1, shortTerm: c.st - 1 },
        { date: '2026-Q1', longTerm: c.lt,     midTerm: c.mt,     shortTerm: c.st },
      ],
      forecast: {
        base:     { label: 'Базовый',    probability: 60, chiIn5y: Math.round(c.mt * 1.05), chiIn10y: Math.round(c.mt * 1.08), description: 'Текущие тренды сохраняются.' },
        positive: { label: 'Позитивный', probability: 25, chiIn5y: Math.round(c.mt * 1.18), chiIn10y: Math.round(c.mt * 1.25), description: 'Риски реализуются позитивно.' },
        negative: { label: 'Негативный', probability: 15, chiIn5y: Math.round(c.mt * 0.85), chiIn10y: Math.round(c.mt * 0.88), description: 'Риски реализуются негативно.' },
      },
      factors: [],
    },
    capitalFlow: {
      score: c.index, signal: c.signal,
      fdi: { value: 0, yoy: 0, trend: 'flat', history: [] },
      portfolio: { value: 0, yoy: 0, trend: 'flat', history: [] },
      remittances: { value: 0, yoy: 0, trend: 'flat', history: [] },
      reForeign: { value: 0, yoy: 0, trend: 'flat', history: [] },
      geoStructure: [],
    },
    macro: {
      gdpGrowth: c.gdp, inflation: c.infl, cbRate: c.rate, unemployment: 5.0,
      householdDebt: 60, govDebt: 55, tradeBalance: 1.0,
      gdpPerCapita: 15000, population: c.pop, currency: 'USD', updatedAt: 'Март 2026',
    },
    society: { happinessRank: 50, happinessScore: 6.0, hdi: 0.800, gini: 38.0, democracyIndex: 5.0, medianAge: 35.0, populationGrowth: 0.5, militarySafety: 60 },
  })),
]

// ─── ДНЕВНИК ──────────────────────────────────────────────────────
export const DIARY_ENTRIES = [
  {
    id: '1',
    country_slug: 'thailand',
    direction: 'general',
    title: 'Таиланд снизил ставку до 1% — что это означает для инвестора',
    slug: 'thailand-rate-cut-2026',
    lead: 'Банк Таиланда снизил ключевую ставку до 1.0% — исторического минимума. Для инвестора в недвижимость это сигнал снижения стоимости финансирования, но долг домохозяйств в 88% ВВП ограничивает реальный эффект.',
    sections: [
      { type: 'highlight', content: 'BOT снизил ставку до 1.0% — последний раз такое было в 2009 году во время глобального финансового кризиса.', label: 'Ключевой факт' },
      { type: 'text', content: 'Решение принято на фоне замедления ВВП до 1.6% и отрицательной инфляции -0.2%. Центробанк пытается стимулировать экономику но инструмент почти исчерпан.' },
      { type: 'text', content: 'Для рынка недвижимости снижение ставки теоретически позитивно — дешевеет ипотека. Но при долге домохозяйств 88% ВВП большинство тайцев уже не могут брать новые кредиты.' },
      { type: 'data', content: 'CHI изменился: краткосрочная линия +4 пункта (реакция на снижение ставки). Среднесрочная без изменений.', label: 'Влияние на CHI' },
    ],
    tags: ['ставка', 'BOT', 'монетарная политика'],
    signal: 'yellow',
    chi_impact: 4,
    image_url: null,
    views: 1247,
    likes: 84,
    published_at: '2026-02-15',
    updated_at: '2026-02-20',
    is_live: true,
  },
  {
    id: '2',
    country_slug: 'thailand',
    direction: 'real-estate',
    title: 'Пхукет 2026: цены выросли на 3.1% — разбор районов',
    slug: 'phuket-prices-q1-2026',
    lead: 'Рынок недвижимости Пхукета показал рост 3.1% за первый квартал 2026 года несмотря на слабую макроэкономику. Туристический спрос компенсирует слабость внутреннего рынка.',
    sections: [
      { type: 'text', content: 'Пхукет продолжает двигаться по собственной траектории отличной от общего рынка Таиланда. Туристический спрос формирует устойчивую базу арендного рынка.' },
      { type: 'highlight', content: 'Лучшие районы: Банг Тао (+4.8%), Камала (+3.9%), Патонг (+2.1%). Хуже рынка: Равай (+0.8%).', label: 'Динамика по районам' },
    ],
    tags: ['Пхукет', 'цены', 'недвижимость'],
    signal: 'green',
    chi_impact: 2,
    image_url: null,
    views: 892,
    likes: 61,
    published_at: '2026-03-01',
    updated_at: '2026-03-01',
    is_live: false,
  },
  {
    id: '3',
    country_slug: 'uae',
    direction: 'real-estate',
    title: 'Дубай: FDI вырос на 34% — рынок недвижимости реагирует',
    slug: 'dubai-fdi-record-2026',
    lead: 'Прямые иностранные инвестиции в ОАЭ достигли рекорда $30.4 млрд в 2025 году. Рынок недвижимости Дубая уже отреагировал: цены в премиальном сегменте выросли на 18% за год.',
    sections: [
      { type: 'text', content: 'Рекордный FDI подтверждает что Дубай успешно реализует стратегию превращения в глобальный деловой хаб.' },
      { type: 'highlight', content: 'Дубай Marina +22%, Palm Jumeirah +18%, Downtown +15%, JVC +8%.', label: 'Рост цен по районам 2025' },
    ],
    tags: ['Дубай', 'FDI', 'недвижимость'],
    signal: 'green',
    chi_impact: 6,
    image_url: null,
    views: 2341,
    likes: 198,
    published_at: '2026-01-20',
    updated_at: '2026-01-25',
    is_live: false,
  },
  {
    id: '4',
    country_slug: 'georgia',
    direction: 'general',
    title: 'Грузия 2026: ВВП 8.2% — лучшая экономика СНГ',
    slug: 'georgia-gdp-2025-record',
    lead: 'Грузия завершила 2025 год с ростом ВВП 8.2% — лучший показатель среди стран постсоветского пространства. Туристов 7.1 млн — новый рекорд.',
    sections: [
      { type: 'text', content: 'Экономика Грузии продолжает удивлять. Приток IT-специалистов и предпринимателей из России и других стран СНГ создал новый средний класс в Тбилиси.' },
    ],
    tags: ['ВВП', 'Тбилиси', 'рост'],
    signal: 'green',
    chi_impact: 5,
    image_url: null,
    views: 1876,
    likes: 142,
    published_at: '2026-01-15',
    updated_at: '2026-01-15',
    is_live: false,
  },
]

// ─── НЕДВИЖИМОСТЬ ТАИЛАНД ─────────────────────────────────────────
export const THAILAND_REAL_ESTATE = {
  resi: 56,
  signal: 'yellow',
  agentNote: 'Момент приемлемый для консервативного входа. Ставка 1% и туристы 36 млн — позитив. Долг домохозяйств 88% и слабый ВВП 1.6% — тормоза. Лучшая ставка: курортная недвижимость Пхукета под краткосрочную аренду.',
  minEntry: 48000,
  avgYield: '6–7%',
  payback: '3–5 лет',
  districts: [
    { id: 'phuket',    name: 'Пхукет',   pricePerSqm: 85000, rentalYield: 7.2, trend: 3.1, demand: 'high',   signal: 'green' },
    { id: 'bangkok',   name: 'Бангкок',  pricePerSqm: 72000, rentalYield: 5.8, trend: 1.2, demand: 'medium', signal: 'yellow' },
    { id: 'pattaya',   name: 'Паттайя', pricePerSqm: 48000, rentalYield: 8.1, trend: 2.4, demand: 'high',   signal: 'green' },
    { id: 'samui',     name: 'Самуи',    pricePerSqm: 95000, rentalYield: 6.9, trend: 4.2, demand: 'high',   signal: 'green' },
    { id: 'chiangmai', name: 'Чиангмай', pricePerSqm: 38000, rentalYield: 5.1, trend: 0.8, demand: 'low',    signal: 'red' },
  ],
  forecast5y: {
    base:     { label: 'Базовый',    probability: 60, chiIn5y: 58, chiIn10y: 62, description: 'Рост цен 2–3% в год. Доходность аренды стабильна 6–7%.' },
    positive: { label: 'Позитивный', probability: 25, chiIn5y: 72, chiIn10y: 78, description: 'Новые права для иностранцев. FDI возвращается. Цены +5–7% в год.' },
    negative: { label: 'Негативный', probability: 15, chiIn5y: 42, chiIn10y: 45, description: 'Политический кризис. Туризм падает. Цены -15–20% от пика.' },
  },
  forecast10y: {
    base:     { label: 'Базовый',    probability: 55, chiIn5y: 58, chiIn10y: 65, description: 'Восстановление завершено. Новый цикл роста начинается к 2030–2032.' },
    positive: { label: 'Позитивный', probability: 28, chiIn5y: 72, chiIn10y: 82, description: 'Таиланд становится regional hub для удалённой работы и инвестиций.' },
    negative: { label: 'Негативный', probability: 17, chiIn5y: 42, chiIn10y: 48, description: 'Структурные проблемы не решаются. Демография давит на внутренний спрос 10 лет.' },
  },
  legal: [
    { question: 'Может ли иностранец владеть землёй?', answer: 'Нет. Иностранцы не могут владеть землёй напрямую. Доступные форматы: кондоминиум (до 49% иностранной квоты), долгосрочная аренда 30+30 лет, тайская компания.' },
    { question: 'Налоги при покупке', answer: 'Трансферный налог 2%, гербовый сбор 0.5% или штраф 3.3% за быструю продажу, НДС 7% для новостроек. Итого ~2.5% при обычной сделке.' },
    { question: 'Налог на аренду', answer: '15% подоходный налог на арендный доход для нерезидентов.' },
    { question: 'Налог при продаже', answer: 'Удерживается у источника: 1% от стоимости или 5% от дохода — меньшее.' },
  ],
  checklist: [
    { step: '01', title: 'Проверить сигнал CHI и RESI', description: 'Убедиться что индекс ≥ 50 для выбранного района' },
    { step: '02', title: 'Рассчитать доходность', description: 'Использовать калькулятор с реальными данными по аренде' },
    { step: '03', title: 'Выбрать район и тип объекта', description: 'Сравнить районы по карте, выбрать под свою цель' },
    { step: '04', title: 'Изучить юридические условия', description: 'Кондо vs аренда земли vs тайская компания' },
    { step: '05', title: 'Найти застройщика / агента', description: 'Проверить лицензию, историю проектов, отзывы' },
    { step: '06', title: 'Открыть счёт в тайском банке', description: 'Bangkok Bank, Kasikorn — необходим для сделки' },
    { step: '07', title: 'Перевести деньги через FET', description: 'Foreign Exchange Transaction — обязательно для кондо' },
  ],
}

// ─── ХЕЛПЕРЫ ──────────────────────────────────────────────────────
export function getCountry(slug) {
  return COUNTRIES.find(c => c.slug === slug)
}

export function getEntriesByCountry(slug) {
  return DIARY_ENTRIES.filter(e => e.country_slug === slug)
}
